import type {
  ContestItem,
  EventItem,
  FeaturedCardItem,
  HeroAction,
  LeaderboardEntry,
  LeaderboardPeriod,
  HowToStep,
  MarketplaceListingItem,
  NavLink,
  StorePackItem,
} from "@/types/upshot";

export const navLinks: NavLink[] = [
  { href: "/store", label: "Store" },
  { href: "/contests", label: "Contests" },
  { href: "/marketplace", label: "Marketplace" },
  { href: "/events", label: "Events" },
  { href: "/leaderboard", label: "Leaderboard" },
];

export const heroActions: HeroAction[] = [
  { href: "/claim", label: "Claim your free card", variant: "primary" },
  { href: "/store", label: "Buy a pack", variant: "secondary" },
];

export const howToSteps: HowToStep[] = [
  {
    description: "Buy a pack and open it to reveal prediction cards.",
    href: "/store",
    mediaSrc: "/videos/onboard/open-mystery-packs-compressed.mp4",
    title: "Open Mystery Packs",
  },
  {
    description: "Each card comes with a prediction, prize and resolution date.",
    mediaSrc: "/videos/onboard/each-card-is-a-prediction-compressed.mp4",
    title: "Each Card is a Prediction",
  },
  {
    description: "If your card comes true, you win cash / prizes from Cards & Monthly Payouts.",
    mediaSrc: "/videos/onboard/win-cash-prizes-compressed.mp4",
    title: "Win Cash Prizes",
  },
  {
    description: "Login daily to claim a Free Gift. Collect streaks for more Gifts!",
    mediaSrc: "/videos/onboard/daily-free-gifts-compressed.mp4",
    title: "Daily Free Gifts",
  },
  {
    description: "Build card lineups and compete against other players to win cash!",
    mediaSrc: "/videos/onboard/join-contests-compressed.mp4",
    title: "Join Contests",
  },
  {
    description: "Start with a pack or claim a free card to see how predictions work.",
    mediaSrc: "/videos/onboard/open-pack-now-compressed.mp4",
    title: "Open Your First Pack Now!",
  },
];

const repeatEventThumbnails = (heroImage: string) => Array.from({ length: 8 }, () => heroImage);

export const featuredEvents: EventItem[] = [
  {
    category: "Sports",
    categoryIcon: "/images/categories/sports.svg",
    eventType: "cash",
    heroImage: "/images/events/japan-f1-event.png",
    href: "/event/cmmu4p2w7cf1q2imurbvldwva",
    statusLabel: "Event has ended",
    listingStatus: "resolved",
    thumbnails: [
      "/images/events/japan-f1-card-1.png",
      "/images/events/japan-f1-card-2.png",
      "/images/events/japan-f1-card-3.png",
      "/images/events/japan-f1-card-4.png",
      "/images/events/japan-f1-card-1.png",
      "/images/events/japan-f1-card-2.png",
      "/images/events/japan-f1-card-3.png",
      "/images/events/japan-f1-card-4.png",
    ],
    title: "Japan F1 GP: Fastest Qualifier (Pole Position)",
  },
  {
    category: "Sports",
    categoryIcon: "/images/categories/sports.svg",
    eventType: "cash",
    heroImage: "/images/events/ncaa-event.png",
    href: "/event/cmmp521pg3gol2hprd8s6orwa",
    statusLabel: "in 9 days",
    listingStatus: "active",
    thumbnails: [
      "/images/events/ncaa-card-1.png",
      "/images/events/ncaa-card-2.png",
      "/images/events/ncaa-card-1.png",
      "/images/events/ncaa-card-2.png",
      "/images/events/ncaa-card-1.png",
      "/images/events/ncaa-card-2.png",
      "/images/events/ncaa-card-1.png",
      "/images/events/ncaa-card-2.png",
    ],
    title: "NCAA Men’s Championship Comes Down To Five Or Fewer",
  },
];

function createLiveEvent({
  badgeLabel,
  category,
  categoryIcon,
  eventType,
  heroImage,
  href,
  isFeatured,
  resolutionDate,
  title,
}: Pick<
  EventItem,
  "badgeLabel" | "category" | "categoryIcon" | "eventType" | "heroImage" | "href" | "isFeatured" | "resolutionDate" | "title"
>): EventItem {
  return {
    badgeLabel,
    category,
    categoryIcon,
    eventType,
    heroImage,
    href,
    isFeatured,
    listingStatus: "active",
    resolutionDate,
    statusLabel: badgeLabel ?? "",
    thumbnails: repeatEventThumbnails(heroImage),
    title,
  };
}

export const eventListings: EventItem[] = [
  createLiveEvent({
    badgeLabel: "in over 42 years",
    category: "Sports",
    categoryIcon: "/images/categories/sports.svg",
    eventType: "instant-win",
    heroImage: "/images/events/live/f1-au-gp-instant-winners.png",
    href: "/event/cmm8vp91w0j5m2hry0l2c3p2v",
    isFeatured: true,
    resolutionDate: "Jan 1, 2069",
    title: "F1 AU GP: Instant Winners",
  }),
  createLiveEvent({
    badgeLabel: "in over 42 years",
    category: "Entertainment",
    categoryIcon: "/images/categories/entertainment.svg",
    eventType: "instant-win",
    heroImage: "/images/events/live/2026-oscars-instant-winners-ii.png",
    href: "/event/cmmeinwji1kbr2hmgkib3poex",
    isFeatured: true,
    resolutionDate: "Jan 1, 2069",
    title: "2026 Oscars: Instant Winners II",
  }),
  createLiveEvent({
    badgeLabel: "in over 42 years",
    category: "Entertainment",
    categoryIcon: "/images/categories/entertainment.svg",
    eventType: "instant-win",
    heroImage: "/images/events/live/2026-oscars-instant-winners.png",
    href: "/event/cmme7rssp1atw2hr2vb43jwof",
    isFeatured: true,
    resolutionDate: "Jan 1, 2069",
    title: "2026 Oscars: Instant Winners",
  }),
  createLiveEvent({
    badgeLabel: "in over 2 years",
    category: "Finance",
    categoryIcon: "/images/categories/finance.svg",
    eventType: "cash",
    heroImage: "/images/events/live/ticker-day-arrives-spacex-stock-symbol.png",
    href: "/event/cmlta8pvw00182hqnjxuggxhm",
    isFeatured: true,
    resolutionDate: "Dec 30, 2028",
    title: "Ticker Day Arrives as SpaceX Unveils Its Stock Symbol",
  }),
  createLiveEvent({
    badgeLabel: "in 9 months",
    category: "Internet Culture",
    categoryIcon: "/images/categories/internet-culture.svg",
    eventType: "cash",
    heroImage: "/images/events/live/mrbeast-500-million-youtube-subscribers.png",
    href: "/event/cmmet3qsa23pm2hr2r53fwzvq",
    resolutionDate: "Dec 31, 2026",
    title: "MrBeast Hits 500 Million YouTube Subscribers",
  }),
  createLiveEvent({
    badgeLabel: "in 9 months",
    category: "Politics",
    categoryIcon: "/images/categories/politics.svg",
    eventType: "cash",
    heroImage: "/images/events/live/epstein-documents-public-stage.png",
    href: "/event/cmnfqj4tm6dth2hmh5yz1m5rf",
    resolutionDate: "Dec 30, 2026",
    title: "A New Wave of Epstein Documents Hits the Public Stage",
  }),
  createLiveEvent({
    badgeLabel: "in 9 months",
    category: "Entertainment",
    categoryIcon: "/images/categories/entertainment.svg",
    eventType: "cash",
    heroImage: "/images/events/live/celebrity-marriage-meltdown-2026.png",
    href: "/event/cmmumoimhdoc12it4v7pfn5iw",
    resolutionDate: "Dec 30, 2026",
    title: "Celebrity Marriage Meltdown 2026",
  }),
  createLiveEvent({
    badgeLabel: "in 9 months",
    category: "Politics",
    categoryIcon: "/images/categories/politics.svg",
    eventType: "cash",
    heroImage: "/images/events/live/alien-life-before-2027.png",
    href: "/event/cmmetunk424fj2hmgqwvrujd1",
    resolutionDate: "Dec 30, 2026",
    title: "US Government Confirms Alien Life Before 2027",
  }),
  createLiveEvent({
    badgeLabel: "in 9 months",
    category: "Entertainment",
    categoryIcon: "/images/categories/entertainment.svg",
    eventType: "cash",
    heroImage: "/images/events/live/kylie-timothee-engagement-watch-2026.png",
    href: "/event/cmlyybbml00jv2hnrfi09bx7p",
    resolutionDate: "Dec 30, 2026",
    title: "Kylie Jenner and Timothee Chalamet Engagement Watch 2026",
  }),
  createLiveEvent({
    badgeLabel: "in 6 months",
    category: "Crypto",
    categoryIcon: "/images/categories/crypto.svg",
    eventType: "cash",
    heroImage: "/images/events/live/sam-bankman-fried-walks-free-by-summer-2026.png",
    href: "/event/cmlyy429c00iu2hnur1ivka4u",
    resolutionDate: "Sep 22, 2026",
    title: "Sam Bankman-Fried Walks Free by Summer (2026)",
  }),
  createLiveEvent({
    badgeLabel: "in 3 months",
    category: "Finance",
    categoryIcon: "/images/categories/finance.svg",
    eventType: "cash",
    heroImage: "/images/events/live/how-many-4t-titans-stand-by-mid-2026.png",
    href: "/event/cmnfqfqrv6d2w2hmhxg0wdw0p",
    resolutionDate: "Jun 29, 2026",
    title: "How Many $4T Titans Stand by Mid-2026",
  }),
  createLiveEvent({
    badgeLabel: "in about 1 month",
    category: "Gaming",
    categoryIcon: "/images/categories/gaming.svg",
    eventType: "cash",
    heroImage: "/images/events/live/valorant-vct-pacific-stage-1-championship-winner-2026.png",
    href: "/event/cmm22epzp01uu2hmr4klinovg",
    resolutionDate: "May 17, 2026",
    title: "Valorant VCT Pacific: Stage 1 Championship Winner (2026)",
  }),
];

export const allEvents: EventItem[] = [...featuredEvents, ...eventListings];

export const featuredContests: ContestItem[] = [
  {
    cardsRequired: 3,
    categories: [{ icon: "/images/categories/sports.svg", label: "Sports" }],
    ctaLabel: "Entries Closed • View Contest",
    endsIn: "37:12:09",
    href: "/contests/cmmpzlegf4ejf2imuln7ki48p",
    lineupLockLabel: "Lineup Lock",
    lineupLockNote: "Locked",
    lineupLockValue: "March 27 at 22:00 UTC",
    poster: "/images/contests/pick-3-sports-madness.png",
    prizePool: "$1,164.22",
    resolutionLabel: "Contest Complete",
    resolutionNote: "Prizes distributed",
    resolutionValue: "March 30 at 14:00 UTC",
    status: "completed",
    title: "Pick 3: Sports Madness",
  },
  {
    cardsRequired: 5,
    categories: [
      { icon: "/images/categories/entertainment.svg", label: "Entertainment" },
      { icon: "/images/categories/internet-culture.svg", label: "Internet Culture" },
      { icon: "/images/categories/gaming.svg", label: "Gaming" },
      { icon: "/images/categories/sports.svg", label: "Sports" },
    ],
    ctaLabel: "View Contest",
    endsIn: "17d",
    href: "/contests/cmmod8vdo24e52it43mivwexf",
    lineupLockLabel: "Lineup Lock",
    lineupLockNote: "Last chance to submit",
    lineupLockValue: "April 1 at 18:00 UTC",
    poster: "/images/contests/pick-5-mid-march-prime-time.png",
    prizePool: "$2,409.1",
    resolutionLabel: "Contest Complete",
    resolutionNote: "Prizes distributed",
    resolutionValue: "April 15 at 18:00 UTC",
    status: "open",
    title: "Pick 5: Mid-March Prime Time",
  },
  {
    cardsRequired: 5,
    categories: [
      { icon: "/images/categories/finance.svg", label: "Finance" },
      { icon: "/images/categories/crypto.svg", label: "Crypto" },
      { icon: "/images/categories/politics.svg", label: "Politics" },
    ],
    ctaLabel: "Entries Closed • View Contest",
    endsIn: "3d",
    href: "/contests/cmm303m3502q92inwd2qle5u6",
    lineupLockLabel: "Lineup Lock",
    lineupLockNote: "Locked",
    lineupLockValue: "March 15 at 14:00 UTC",
    poster: "/images/contests/pick-5-march-markets-and-power.png",
    prizePool: "$4,607.46",
    resolutionLabel: "Contest Complete",
    resolutionNote: "Prizes distributed",
    resolutionValue: "April 1 at 14:00 UTC",
    status: "completed",
    title: "Pick 5: March Markets and Power",
  },
  {
    cardsRequired: 5,
    categories: [
      { icon: "/images/categories/entertainment.svg", label: "Entertainment" },
      { icon: "/images/categories/internet-culture.svg", label: "Internet Culture" },
      { icon: "/images/categories/sports.svg", label: "Sports" },
    ],
    ctaLabel: "Entries Closed • View Contest",
    endsIn: "3d",
    href: "/contests/cmm2zme9i01q92iscvgo02wtw",
    lineupLockLabel: "Lineup Lock",
    lineupLockNote: "Locked",
    lineupLockValue: "March 15 at 14:00 UTC",
    poster: "/images/contests/pick-5-march-screens-and-scoreboards.png",
    prizePool: "$4,652.63",
    resolutionLabel: "Contest Complete",
    resolutionNote: "Prizes distributed",
    resolutionValue: "April 1 at 14:00 UTC",
    status: "completed",
    title: "Pick 5: March Screens and Scoreboards",
  },
];

export const contestListings: ContestItem[] = [
  {
    cardsRequired: 5,
    categories: [{ icon: "/images/categories/sports.svg", label: "Sports" }],
    ctaLabel: "View Contest",
    endsIn: "5d",
    href: "/contests/ncaa-pick-5-unlimited",
    lineupLockLabel: "Lineup Lock",
    lineupLockNote: "Last chance to submit",
    lineupLockValue: "April 5 at 02:10 UTC",
    poster: "/images/contests/live/ncaa-pick-5-unlimited.png",
    prizePool: "$410.72",
    resolutionLabel: "Contest Complete",
    resolutionNote: "Prizes distributed",
    resolutionValue: "April 8 at 14:50 UTC",
    status: "open",
    title: "NCAA Pick 5 Unlimited",
  },
  {
    cardsRequired: 3,
    categories: [{ icon: "/images/categories/sports.svg", label: "Sports" }],
    ctaLabel: "View Contest",
    endsIn: "5d",
    href: "/contests/ncaa-pick-3-unlimited",
    lineupLockLabel: "Lineup Lock",
    lineupLockNote: "Last chance to submit",
    lineupLockValue: "April 5 at 02:09 UTC",
    poster: "/images/contests/live/ncaa-pick-3-unlimited.png",
    prizePool: "$410.68",
    resolutionLabel: "Contest Complete",
    resolutionNote: "Prizes distributed",
    resolutionValue: "April 8 at 14:50 UTC",
    status: "open",
    title: "NCAA Pick 3 Unlimited",
  },
  {
    cardsRequired: 3,
    categories: [{ icon: "/images/categories/sports.svg", label: "Sports" }],
    ctaLabel: "Entries Closed • View Contest",
    endsIn: "3d",
    href: "/contests/pick-3-early-april-sports",
    lineupLockLabel: "Lineup Lock",
    lineupLockNote: "Locked",
    lineupLockValue: "April 3 at 01:25 UTC",
    poster: "/images/contests/live/pick-3-early-april-sports.png",
    prizePool: "$611.62",
    resolutionLabel: "Contest Complete",
    resolutionNote: "Prizes distributed",
    resolutionValue: "April 6 at 13:45 UTC",
    status: "live",
    title: "Pick 3: Early April Sports",
  },
  {
    cardsRequired: 5,
    categories: [
      { icon: "/images/categories/entertainment.svg", label: "Entertainment" },
      { icon: "/images/categories/internet-culture.svg", label: "Internet Culture" },
      { icon: "/images/categories/gaming.svg", label: "Gaming" },
      { icon: "/images/categories/sports.svg", label: "Sports" },
    ],
    ctaLabel: "Entries Closed • View Contest",
    endsIn: "12d",
    href: "/contests/pick-5-mid-march-prime-time",
    lineupLockLabel: "Lineup Lock",
    lineupLockNote: "Locked",
    lineupLockValue: "April 1 at 18:00 UTC",
    poster: "/images/contests/live/pick-5-mid-march-prime-time.png",
    prizePool: "$2,776.86",
    resolutionLabel: "Contest Complete",
    resolutionNote: "Prizes distributed",
    resolutionValue: "April 15 at 18:00 UTC",
    status: "live",
    title: "Pick 5: Mid-March Prime Time",
  },
];

export const allContests: ContestItem[] = [...featuredContests, ...contestListings];

export const featuredCards: FeaturedCardItem[] = [
  {
    burned: 0,
    claimed: 5,
    href: "/card-detail/cmmur9r6fedjf2hpr0enuy12v",
    image: "/images/cards/featured-1.png",
    supply: 5,
    title: "Cuba Falls to Washington",
  },
  {
    burned: 0,
    claimed: 15,
    href: "/card-detail/cmmur4gd5e7zr2it4z6p2scwf",
    image: "/images/cards/featured-2.png",
    supply: 15,
    title: "Washington and Tehran Declare Ceasefire",
  },
  {
    burned: 0,
    claimed: 34,
    href: "/card-detail/cmmu3wq9ycf1e2it4x76rd4ak",
    image: "/images/cards/featured-3.png",
    supply: 40,
    title: "Racing Bulls Coldest Moment at the Japan F1 GP",
  },
  {
    burned: 0,
    claimed: 12,
    href: "/card-detail/cmn2rdqip7vce2hlcixp6bxs1",
    image: "/images/cards/featured-4.png",
    supply: 13,
    title: "Super Mario Galaxy Opening Weekend Hits High Score",
  },
  {
    burned: 0,
    claimed: 13,
    href: "/card-detail/cmn2pq9ij7qrn2hlcmpv04nhg",
    image: "/images/cards/featured-5.png",
    supply: 13,
    title: "Jannik Sinner Wins Miami Open",
  },
  {
    burned: 0,
    claimed: 18,
    href: "/card-detail/cmn2r25kx7vvo2itc2otd65dx",
    image: "/images/cards/featured-6.png",
    supply: 19,
    title: "Secret Rare from Mega Evolution - Perfect Order",
  },
  {
    burned: 0,
    claimed: 3,
    href: "/card-detail/cmn2qhnz37sq32hlc80kcw7z8",
    image: "/images/cards/featured-7.png",
    supply: 3,
    title: "Upshot Q1 Mainnet Pack Ripping Goes Full Send",
  },
  {
    burned: 0,
    claimed: 12,
    href: "/card-detail/cmn2s7nbf7yd12hlc4bpar89m",
    image: "/images/cards/featured-8.png",
    supply: 12,
    title: "X Dislike Button Rolls Out Mid Cycle",
  },
];

const homepageFeaturedEventHeroMap: Partial<Record<EventItem["category"], string>> = {
  Sports: "/images/events/japan-f1-event.png",
  Entertainment: "/images/events/live/celebrity-marriage-meltdown-2026.png",
  Finance: "/images/events/live/ticker-day-arrives-spacex-stock-symbol.png",
  "Internet Culture": "/images/events/live/mrbeast-500-million-youtube-subscribers.png",
  Politics: "/images/events/live/epstein-documents-public-stage.png",
  Crypto: "/images/events/live/sam-bankman-fried-walks-free-by-summer-2026.png",
  Gaming: "/images/events/live/valorant-vct-pacific-stage-1-championship-winner-2026.png",
};

const homepageFeaturedEventThumbnailPool = featuredCards.map(({ image }) => image);

function createHomepageFeaturedEventThumbnails() {
  const baseThumbnails = Array.from({ length: 4 }, (_, index) => {
    return homepageFeaturedEventThumbnailPool[index % homepageFeaturedEventThumbnailPool.length];
  });

  return [...baseThumbnails, ...baseThumbnails];
}

export const homepageFeaturedEvents: EventItem[] = eventListings.slice(0, 6).map((event) => ({
  ...event,
  heroImage: homepageFeaturedEventHeroMap[event.category] ?? event.heroImage,
  thumbnails: createHomepageFeaturedEventThumbnails(),
}));

const marketplaceBlueprints = [
  { available: 10, burned: 2479, cardIndex: 0, editionLabel: "1 / 5", price: "0.034" },
  { available: 2, burned: 1801, cardIndex: 1, editionLabel: "2 / 10", price: "0.021" },
  { available: 7, burned: 646, cardIndex: 2, editionLabel: "1 / 3", price: "0.057" },
  { available: 10, burned: 698, cardIndex: 3, editionLabel: "4 / 15", price: "0.018" },
  { available: 4, burned: 1320, cardIndex: 4, editionLabel: "1 / 8", price: "0.026" },
  { available: 6, burned: 934, cardIndex: 5, editionLabel: "3 / 12", price: "0.041" },
  { available: 1, burned: 2875, cardIndex: 6, editionLabel: "1 / 2", price: "0.062" },
  { available: 9, burned: 511, cardIndex: 7, editionLabel: "5 / 25", price: "0.015" },
  { available: 3, burned: 1408, cardIndex: 3, editionLabel: "2 / 7", price: "0.033" },
  { available: 8, burned: 902, cardIndex: 4, editionLabel: "6 / 20", price: "0.019" },
  { available: 5, burned: 1766, cardIndex: 5, editionLabel: "1 / 4", price: "0.049" },
  { available: 2, burned: 1084, cardIndex: 6, editionLabel: "2 / 9", price: "0.028" },
  { available: 6, burned: 820, cardIndex: 7, editionLabel: "1 / 6", price: "0.031" },
  { available: 12, burned: 441, cardIndex: 0, editionLabel: "7 / 30", price: "0.014" },
  { available: 3, burned: 1206, cardIndex: 1, editionLabel: "1 / 11", price: "0.036" },
  { available: 1, burned: 2220, cardIndex: 2, editionLabel: "2 / 5", price: "0.054" },
  { available: 9, burned: 594, cardIndex: 6, editionLabel: "3 / 18", price: "0.022" },
  { available: 2, burned: 1507, cardIndex: 5, editionLabel: "1 / 9", price: "0.038" },
  { available: 4, burned: 1292, cardIndex: 4, editionLabel: "2 / 6", price: "0.043" },
  { available: 11, burned: 488, cardIndex: 3, editionLabel: "5 / 20", price: "0.017" },
  { available: 1, burned: 3044, cardIndex: 2, editionLabel: "1 / 1", price: "0.081" },
  { available: 5, burned: 970, cardIndex: 1, editionLabel: "3 / 8", price: "0.027" },
  { available: 7, burned: 742, cardIndex: 0, editionLabel: "2 / 14", price: "0.024" },
  { available: 3, burned: 1168, cardIndex: 7, editionLabel: "1 / 10", price: "0.029" },
  { available: 14, burned: 322, cardIndex: 5, editionLabel: "8 / 40", price: "0.012" },
] as const;

const marketplaceCardMeta = [
  {
    category: "Politics",
    categoryIcon: "/images/categories/politics.svg",
    eventTitle: "Cuba and Washington Brinkmanship",
    eventType: "cash",
    rarity: "rare",
  },
  {
    category: "Politics",
    categoryIcon: "/images/categories/politics.svg",
    eventTitle: "Washington and Tehran Ceasefire Window",
    eventType: "cash",
    rarity: "uncommon",
  },
  {
    category: "Sports",
    categoryIcon: "/images/categories/sports.svg",
    eventTitle: "Japan F1 GP Performance Board",
    eventType: "gold",
    rarity: "common",
  },
  {
    category: "Gaming",
    categoryIcon: "/images/categories/gaming.svg",
    eventTitle: "Super Mario Galaxy Opening Weekend",
    eventType: "shots",
    rarity: "uncommon",
  },
  {
    category: "Sports",
    categoryIcon: "/images/categories/sports.svg",
    eventTitle: "Miami Open Men’s Final",
    eventType: "cash",
    rarity: "rare",
  },
  {
    category: "Entertainment",
    categoryIcon: "/images/categories/entertainment.svg",
    eventTitle: "Mega Evolution - Perfect Order",
    eventType: "gold",
    isFeatured: true,
    rarity: "legendary",
  },
  {
    category: "Crypto",
    categoryIcon: "/images/categories/crypto.svg",
    eventTitle: "Upshot Q1 Mainnet Pack Ripping",
    eventType: "instant-win",
    isFeatured: true,
    rarity: "legendary",
  },
  {
    category: "Internet Culture",
    categoryIcon: "/images/categories/internet-culture.svg",
    eventTitle: "X Dislike Button Rollout",
    eventType: "shots",
    rarity: "common",
  },
] as const satisfies ReadonlyArray<
  Pick<MarketplaceListingItem, "category" | "categoryIcon" | "eventTitle" | "eventType" | "isFeatured" | "rarity">
>;

export const marketplaceListings: MarketplaceListingItem[] = marketplaceBlueprints.map((blueprint, index) => {
  const card = featuredCards[blueprint.cardIndex];
  const metadata = marketplaceCardMeta[blueprint.cardIndex];

  return {
    available: blueprint.available,
    buttonLabel: "Buy now",
    burned: blueprint.burned,
    category: metadata.category,
    categoryIcon: metadata.categoryIcon,
    editionLabel: blueprint.editionLabel,
    eventTitle: metadata.eventTitle,
    eventType: metadata.eventType,
    href: `${card.href}?listing=${index + 1}`,
    image: card.image,
    isFeatured: "isFeatured" in metadata ? metadata.isFeatured : undefined,
    price: blueprint.price,
    priceSuffix: "ETH",
    rarity: metadata.rarity,
    title: card.title,
  };
});

export const storePacks: StorePackItem[] = [
  {
    buttonLabel: "Sold Out",
    description:
      "The stakes are rising. March Mayhem Pack #3 brings the intensity of the tournament to its peak, where tempo spikes, stars take over, and defenses either hold or collapse. Every possession matters, and every moment can shift a run. From explosive scoring bursts to lockdown defensive stands, this pack captures the chaos, control, and clutch performances that define March.",
    href: "/store/march-mayhem-3",
    imageAlt: "March Mayhem #3 pack art",
    imageSrc:
      "https://upshot.cards/_next/image?url=https%3A%2F%2Fassets.upshotcards.net%2Fuploads%2F1774924629683-image.png&w=1920&q=75",
    includedCardIndexes: [0, 1, 2],
    isSoldOut: true,
    price: "$5.65",
    priceSuffix: "USD",
    revealCount: "5 cards",
    statusLabel: "SOLD OUT",
    title: "March Mayhem #3",
  },
  {
    buttonLabel: "Sold Out",
    description:
      "Knights, underdogs, titans, and gods. The FA Cup quarter-finals throw up everything English football has to offer across one weekend in April. Arsenal at Southampton. Chelsea vs Port Vale. Man City vs Liverpool. West Ham vs Leeds. Four fixtures, three divisions, one road to Wembley. 24 events. 100+ cards. Match winners, total goals, cards, extra time, and player of the match across every fixture. Collect the quarter-finals.",
    href: "/store/fa-cup-quarter-finals",
    imageAlt: "FA Cup Quarter-Finals pack art",
    imageSrc:
      "https://upshot.cards/_next/image?url=https%3A%2F%2Fassets.upshotcards.net%2Fuploads%2F1774492107684-image.png&w=1920&q=75",
    includedCardIndexes: [2, 4, 7],
    isSoldOut: true,
    price: "$5.65",
    priceSuffix: "USD",
    revealCount: "5 cards",
    statusLabel: "SOLD OUT",
    title: "FA Cup Quarter-Finals",
  },
  {
    buttonLabel: "Sold Out",
    description:
      "The madness deepens. The March Mayhem #2 Prediction Pack brings a fresh wave of prediction cards tied to the next round of storylines from the 2026 NCAA Men's Tournament. Upsets, blowouts, Cinderella runs, and stat lines that rewrite the bracket. Each card represents a possible outcome waiting to play out as the field narrows toward the Final Four. Open packs, collect outcomes, and see which predictions survive the cut.",
    href: "/store/march-mayhem-2",
    imageAlt: "March Mayhem #2 pack art",
    imageSrc:
      "https://upshot.cards/_next/image?url=https%3A%2F%2Fassets.upshotcards.net%2Fuploads%2F1774321873069-image.png&w=1920&q=75",
    includedCardIndexes: [0, 3, 5],
    isSoldOut: true,
    price: "$5.65",
    priceSuffix: "USD",
    revealCount: "5 cards",
    statusLabel: "SOLD OUT",
    title: "March Mayhem #2",
  },
  {
    buttonLabel: "Sold Out",
    description:
      "Network Effect #1 captures the moments that ripple across the internet and reshape attention in real time. From viral surges to unexpected breakouts, each outcome reflects how quickly influence compounds when the right signal hits the network.",
    href: "/store/network-effect-1",
    imageAlt: "Network Effect #1 pack art",
    imageSrc:
      "https://upshot.cards/_next/image?url=https%3A%2F%2Fassets.upshotcards.net%2Fuploads%2F1773907183631-image.png&w=1920&q=75",
    includedCardIndexes: [1, 5, 6],
    isSoldOut: true,
    price: "$5.65",
    priceSuffix: "USD",
    revealCount: "5 cards",
    statusLabel: "SOLD OUT",
    title: "Network Effect #1",
  },
  {
    buttonLabel: "Sold Out",
    description:
      "The first Power & Profit drop stacks politics, finance, and culture into one volatile window resolving through early April 2026. Rate decisions, inflation prints, crypto weekly closes, and a precious metals race cover the money side. Government shutdowns, Iran ceasefire odds, Cuba escalation, and recession calls handle the power plays. And because no pack is complete without chaos: Pokemon card markets, Grok getting banned in France, Epstein Island PokeStops, and the internet's most Googled human.",
    href: "/store/power-profit-1-prediction-pack",
    imageAlt: "Power & Profit #1 Prediction Pack art",
    imageSrc:
      "https://upshot.cards/_next/image?url=https%3A%2F%2Fassets.upshotcards.net%2Fuploads%2F1773809941383-image.png&w=1920&q=75",
    includedCardIndexes: [0, 2, 5],
    isSoldOut: true,
    price: "$5.65",
    priceSuffix: "USD",
    revealCount: "5 cards",
    statusLabel: "SOLD OUT",
    title: "Power & Profit #1 Prediction Pack",
  },
  {
    buttonLabel: "Sold Out",
    description:
      "The 2026 Formula 1 season returns to Suzuka, and this pack covers every angle of one of the calendar's most unforgiving circuits. From Sprint Race and Pole Position to Fastest Lap, Driver of the Day, first-lap drama, last-place finishes, and the Grand Prix winner, every outcome lands as a collectible card. Suzuka's figure-eight layout and high-speed esses punish mistakes and reward commitment, making it one of the purest tests of driver and machine on the calendar. Chase legendary Upshot X 1/1 editions, high-supply skill plays, and volatile sweeps outcomes where a single misjudgment through 130R changes everything.",
    href: "/store/japanese-grand-prix-prediction-pack",
    imageAlt: "Japanese Grand Prix Prediction Pack art",
    imageSrc:
      "https://upshot.cards/_next/image?url=https%3A%2F%2Fassets.upshotcards.net%2Fuploads%2F1773755361707-image.png&w=1920&q=75",
    includedCardIndexes: [2, 3, 4],
    isSoldOut: true,
    price: "$5.65",
    priceSuffix: "USD",
    revealCount: "5 cards",
    statusLabel: "SOLD OUT",
    title: "Japanese Grand Prix Prediction Pack",
  },
  {
    buttonLabel: "Sold Out",
    description:
      "The madness begins. The March Mayhem #1 Prediction Pack features a collection of prediction cards tied to key storylines and statistical outcomes from the 2026 NCAA Men's Tournament. From overtime thrillers and buzzer-beaters to three-point explosions and tournament chaos, each card represents a possible outcome that could unfold during March's biggest basketball event. Open packs, collect outcomes, and see which predictions become reality as the tournament unfolds.",
    href: "/store/march-mayhem-1-prediction-pack",
    imageAlt: "March Mayhem #1 Prediction Pack art",
    imageSrc:
      "https://upshot.cards/_next/image?url=https%3A%2F%2Fassets.upshotcards.net%2Fuploads%2F1773495616608-image.png&w=1920&q=75",
    includedCardIndexes: [1, 3, 7],
    isSoldOut: true,
    price: "$5.65",
    priceSuffix: "USD",
    revealCount: "5 cards",
    statusLabel: "SOLD OUT",
    title: "March Mayhem #1 Prediction Pack",
  },
  {
    buttonLabel: "Sold Out",
    description:
      "The 2026 Formula 1 season hits Shanghai for its first Sprint weekend, and this pack captures every decisive moment. From Sprint Race and Pole Position to Fastest Lap, Driver of the Day, first-race chaos, last-place heartbreak, and the ultimate prize - the Grand Prix winner - every outcome is in play. Whether it's Mercedes extending their dominance or a shock result on the high-tyre-degradation Shanghai circuit, China always delivers unpredictability. Chase legendary Upshot X 1/1 editions, high-supply skill plays, and volatile sweeps outcomes that can flip on a single corner.",
    href: "/store/chinese-grand-prix-prediction-pack",
    imageAlt: "Chinese Grand Prix Prediction Pack art",
    imageSrc:
      "https://upshot.cards/_next/image?url=https%3A%2F%2Fassets.upshotcards.net%2Fuploads%2F1773147555830-image.png&w=1920&q=75",
    includedCardIndexes: [0, 4, 6],
    isSoldOut: true,
    price: "$5.65",
    priceSuffix: "USD",
    revealCount: "5 cards",
    statusLabel: "SOLD OUT",
    title: "Chinese Grand Prix Prediction Pack",
  },
  {
    buttonLabel: "Sold Out",
    description:
      "The 98th Academy Awards Prediction Pack features collectible cards tied to the biggest categories of the 2026 Oscars. Each card represents a possible outcome from the Academy Awards, covering major technical and creative achievements across film.",
    href: "/store/the-oscars-98th-academy-awards-prediction-pack",
    imageAlt: "The Oscars: 98th Academy Awards Prediction Pack art",
    imageSrc:
      "https://upshot.cards/_next/image?url=https%3A%2F%2Fupshot-assets.b-cdn.net%2F98-academy-awards.png&w=1920&q=75",
    includedCardIndexes: [0, 5, 7],
    isSoldOut: true,
    price: "$5.65",
    priceSuffix: "USD",
    revealCount: "5 cards",
    statusLabel: "SOLD OUT",
    title: "The Oscars: 98th Academy Awards Prediction Pack",
  },
  {
    buttonLabel: "Sold Out",
    description:
      "The 2026 Formula 1 season roars to life at Albert Park, and this pack captures every decisive moment. From Pole Position and Fastest Lap to Driver of the Day, first-race chaos, last-place heartbreak, and the ultimate prize, the race winner, every outcome is in play. Whether it's dominant pace from the front-runners or a shock result from the midfield, Melbourne always delivers unpredictability. Chase legendary Upshot X 1/1 editions, high-supply skill plays, and volatile sweeps outcomes that can flip on a single corner.",
    href: "/store/australian-grand-prix-prediction-pack",
    imageAlt: "Australian Grand Prix Prediction Pack art",
    imageSrc:
      "https://upshot.cards/_next/image?url=https%3A%2F%2Fupshot-assets.b-cdn.net%2Faustralian-grand-prix-prediction-pack%2FAU_GP_2026_Pack-removebg-preview.png&w=1920&q=75",
    includedCardIndexes: [2, 5, 6],
    isSoldOut: true,
    price: "$5.65",
    priceSuffix: "USD",
    revealCount: "5 cards",
    statusLabel: "SOLD OUT",
    title: "Australian Grand Prix Prediction Pack",
  },
  {
    buttonLabel: "Sold Out",
    description:
      "From blockbuster drops to creator milestones, this pack covers the gaming, entertainment, and internet culture events that dominate the conversation.",
    href: "/store/culture-prediction-pack",
    imageAlt: "Culture Prediction Pack art",
    imageSrc:
      "https://upshot.cards/_next/image?url=https%3A%2F%2Farweave.net%2FiKw_nizAX5nb50y0fwGsm2TEAmylEk2JtNwNkER2peU&w=1920&q=75",
    includedCardIndexes: [3, 4, 7],
    isSoldOut: true,
    price: "$5.65",
    priceSuffix: "USD",
    revealCount: "5 cards",
    statusLabel: "SOLD OUT",
    title: "Culture Prediction Pack",
  },
  {
    buttonLabel: "Sold Out",
    description:
      "From market moves to election calls, this pack covers the crypto, finance, and politics events that keep everyone watching.",
    href: "/store/news-and-economy-prediction-pack",
    imageAlt: "News & Economy Prediction Pack art",
    imageSrc:
      "https://upshot.cards/_next/image?url=https%3A%2F%2Farweave.net%2FRtVe5SdnP-Ws63So4dNOAmHa1dgFfnLLvw21qgg0ZLU&w=1920&q=75",
    includedCardIndexes: [0, 1, 6],
    isSoldOut: true,
    price: "$5.65",
    priceSuffix: "USD",
    revealCount: "5 cards",
    statusLabel: "SOLD OUT",
    title: "News & Economy Prediction Pack",
  },
  {
    buttonLabel: "Sold Out",
    description:
      "From clutch plays to breakout stars, this pack captures the hype, drama, and storylines across the world of sports.",
    href: "/store/sports-prediction-pack",
    imageAlt: "Sports Prediction Pack art",
    imageSrc:
      "https://upshot.cards/_next/image?url=https%3A%2F%2Farweave.net%2F7PEwTh6uWSPvuLtbFQdh1dWCxvgi8XfmN-90auyGlt8&w=1920&q=75",
    includedCardIndexes: [1, 2, 4],
    isSoldOut: true,
    price: "$5.65",
    priceSuffix: "USD",
    revealCount: "5 cards",
    statusLabel: "SOLD OUT",
    title: "Sports Prediction Pack",
  },
  {
    buttonLabel: "Sold Out",
    description: "Mystery Pack of Prediction Cards",
    href: "/store/random-pack",
    imageAlt: "Random Pack art",
    imageSrc:
      "https://upshot.cards/_next/image?url=https%3A%2F%2Farweave.net%2FOLWeDVONUsE9ZaBeCIKJSwjvAZ7wqadguemnq0Derk4&w=1920&q=75",
    includedCardIndexes: [2, 6, 7],
    isSoldOut: true,
    price: "$5.65",
    priceSuffix: "USD",
    revealCount: "5 cards",
    statusLabel: "SOLD OUT",
    title: "Random Pack",
  },
];

export const footerLinks: NavLink[] = [
  { href: "/terms", label: "Terms & Conditions" },
  { href: "/privacy", label: "Privacy Policy" },
];

export const socialLinks = [
  { href: "https://x.com/upshot_cards", icon: "/images/social-x.svg", label: "X" },
  { href: "https://discord.com/invite/upshot", icon: "/images/social-discord.svg", label: "Discord" },
] as const;

export const leaderboardEntries: Record<LeaderboardPeriod, LeaderboardEntry[]> = {
  season: [
    {
      name: "Simmo",
      otherBoosts: "1,420",
      prize: "$5,000",
      rank: 1,
      setBoost: "2,180",
      totalXp: "15,840",
      walletTag: "0xsimmo...92a1",
      winningCardXp: "12,240",
    },
    {
      name: "Mamba.eth",
      otherBoosts: "1,240",
      prize: "$2,500",
      rank: 2,
      setBoost: "1,960",
      totalXp: "14,760",
      walletTag: "@mamba",
      winningCardXp: "11,560",
    },
    {
      name: "CardShark",
      otherBoosts: "980",
      prize: "$1,250",
      rank: 3,
      setBoost: "1,720",
      totalXp: "13,520",
      walletTag: "0x8b7e...f143",
      winningCardXp: "10,820",
    },
    {
      name: "AlphaArc",
      otherBoosts: "860",
      prize: "500 Gold",
      rank: 4,
      setBoost: "1,480",
      totalXp: "11,940",
      walletTag: "@alphaarc",
      winningCardXp: "9,600",
    },
    {
      name: "PolePosition",
      otherBoosts: "720",
      prize: "250 Gold",
      rank: 5,
      setBoost: "1,260",
      totalXp: "10,780",
      walletTag: "0xf1au...7782",
      winningCardXp: "8,800",
    },
    {
      name: "NovaTag",
      otherBoosts: "640",
      prize: "100 Gold",
      rank: 6,
      setBoost: "1,120",
      totalXp: "9,960",
      walletTag: "@novatag",
      winningCardXp: "8,200",
    },
    {
      name: "CultureFlip",
      otherBoosts: "590",
      prize: "50 Gold",
      rank: 7,
      setBoost: "980",
      totalXp: "9,220",
      walletTag: "0xcult...4420",
      winningCardXp: "7,650",
    },
    {
      name: "TapeDelayed",
      otherBoosts: "520",
      prize: "25 Gold",
      rank: 8,
      setBoost: "910",
      totalXp: "8,740",
      walletTag: "@tapedelayed",
      winningCardXp: "7,310",
    },
    {
      name: "0xForecast",
      otherBoosts: "470",
      prize: "10 Gold",
      rank: 9,
      setBoost: "860",
      totalXp: "8,180",
      walletTag: "0xfore...210c",
      winningCardXp: "6,850",
    },
    {
      name: "DailyClaimr",
      otherBoosts: "430",
      prize: "5 Gold",
      rank: 10,
      setBoost: "790",
      totalXp: "7,820",
      walletTag: "@dailyclaimr",
      winningCardXp: "6,600",
    },
  ],
  lifetime: [
    {
      name: "Simmo",
      otherBoosts: "8,940",
      prize: "$10,000",
      rank: 1,
      setBoost: "12,460",
      totalXp: "86,420",
      walletTag: "0xsimmo...92a1",
      winningCardXp: "65,020",
    },
    {
      name: "Mamba.eth",
      otherBoosts: "8,210",
      prize: "$5,000",
      rank: 2,
      setBoost: "11,980",
      totalXp: "81,330",
      walletTag: "@mamba",
      winningCardXp: "61,140",
    },
    {
      name: "CardShark",
      otherBoosts: "7,540",
      prize: "$2,500",
      rank: 3,
      setBoost: "10,860",
      totalXp: "75,680",
      walletTag: "0x8b7e...f143",
      winningCardXp: "57,280",
    },
    {
      name: "AlphaArc",
      otherBoosts: "6,980",
      prize: "Founder Badge",
      rank: 4,
      setBoost: "9,720",
      totalXp: "69,410",
      walletTag: "@alphaarc",
      winningCardXp: "52,710",
    },
    {
      name: "PolePosition",
      otherBoosts: "6,220",
      prize: "Champion Flair",
      rank: 5,
      setBoost: "9,140",
      totalXp: "63,820",
      walletTag: "0xf1au...7782",
      winningCardXp: "48,460",
    },
    {
      name: "NovaTag",
      otherBoosts: "5,870",
      prize: "Legend Title",
      rank: 6,
      setBoost: "8,460",
      totalXp: "58,930",
      walletTag: "@novatag",
      winningCardXp: "44,600",
    },
    {
      name: "CultureFlip",
      otherBoosts: "5,220",
      prize: "Elite Badge",
      rank: 7,
      setBoost: "7,980",
      totalXp: "54,270",
      walletTag: "0xcult...4420",
      winningCardXp: "41,070",
    },
    {
      name: "TapeDelayed",
      otherBoosts: "4,980",
      prize: "OG Flair",
      rank: 8,
      setBoost: "7,410",
      totalXp: "50,610",
      walletTag: "@tapedelayed",
      winningCardXp: "38,220",
    },
    {
      name: "0xForecast",
      otherBoosts: "4,620",
      prize: "Collector Badge",
      rank: 9,
      setBoost: "6,960",
      totalXp: "47,840",
      walletTag: "0xfore...210c",
      winningCardXp: "36,260",
    },
    {
      name: "DailyClaimr",
      otherBoosts: "4,310",
      prize: "Early Access",
      rank: 10,
      setBoost: "6,580",
      totalXp: "45,320",
      walletTag: "@dailyclaimr",
      winningCardXp: "34,430",
    },
  ],
};
